In [184]:
import pandas as pd
import numpy as np

In [633]:
data = pd.read_csv('D:/PGDBA/Competitions/EXL-Acumen/Input.csv')
submit = pd.read_csv('D:\PGDBA\Competitions\EXL-Acumen\submit.csv')

In [634]:
data.head()

UNIQUE_ID  Rev_17_GeoPod  Rev_17_B  Rev_17_C  Vol_17_GeoPod  Vol_17_B  \
0         20      148458.28    648.24       0.0           1533         6   
1         37       48796.95      0.00       0.0            294         0   
2         44        1875.00      0.00       0.0              7         0   
3         48        1009.20      0.00       0.0              8         0   
4         72        9781.23    234.85       0.0             46         1   

   Vol_17_C  Rev_17_GeoPod_Logistics  Rev_17_GeoPod_HR  Rev_17_GeoPod_Finance  \
0         0                   126.33      1.816350e+03              146515.60   
1         0                   209.00      8.974500e+02               47690.50   
2         0                   380.00      0.000000e+00                1495.00   
3         0                     0.00      2.186900e+02                 790.51   
4         0                   274.59      1.710000e-13                9506.64   

   ...  Vol_16_GeoPod_Logistics  Vol_16_GeoPod_HR  Vol_16_GeoPod_Finance  \
0  ...                        1              1461                     57   
1  ...                        1               278                      6   
2  ...                        1                 3                      0   
3  ...                        0                 6                      1   
4  ...                        1                39                      0   

   Vol_16_D  Vol_16_E  Vol_16_F  Vol_16_G  Vol_16_H  Vol_16_I  Attrition_Flag  
0       457         0         0      2350         0         0               0  
1       109         1         0         7         0         0               0  
2         0         0         0         0         0         0               0  
3         0         0         0         0         0         0               0  
4       245         0         0         0         0         0               0  

[5 rows x 62 columns]

In [635]:
data.Market_Segment.unique()

array(['Large Business', 'Small Business'], dtype=object)

In [636]:
len(np.intersect1d(data.UNIQUE_ID,submit.UNIQUE_ID))

0

In [637]:
submit['Attrition_Flag'] = None

In [638]:
all_data = data.append(submit, ignore_index = True)

In [639]:
print(len(data), len(submit), len(all_data))

14601 4000 18601


In [640]:
#all_data[all_data['Attrition_Flag'].isnull()]

In [641]:
all_data['Market_Segment'] = ['1' if x == 'Large Business' else 0 for x in all_data['Market_Segment']]
all_data['Market_Segment'] = all_data['Market_Segment'].astype('int32')
all_data['Market_Segment'] = all_data['Market_Segment'].astype('int32')

In [642]:
#all_data.info()

In [643]:
all_data.Sub_Segment.unique()

array(['Multinational Banks', 'Credit Unions', 'Small Business',
       'Investment Firms', nan], dtype=object)

In [644]:
all_data['Sub_Segment'] = [1 if x == 'Small Business' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'] = [2 if x == 'Investment Firms' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'] = [3 if x == 'Credit Unions' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'] = [4 if x == 'Multinational Banks' else x for x in all_data['Sub_Segment']]
all_data['Sub_Segment'].fillna(0, inplace = True)
all_data['Sub_Segment'] = all_data['Sub_Segment'].astype('int32')

In [645]:
from sklearn.preprocessing import LabelEncoder
labelEnc = LabelEncoder()
#all_data['Sales_Person_Jun_17'] = ['1' if x == 'Unassigned' else x for x in all_data['Sales_Person_Jun_17']]
#all_data['Sales_Person_Jun_17'] = labelEnc.fit_transform(all_data['Sales_Person_Jun_17'])
#all_data['Sales_Person_Jun_17'] = all_data['Sales_Person_Jun_17'].astype('int32')
all_data['RSM_Jun_17'] = labelEnc.fit_transform(all_data['RSM_Jun_17'])
all_data['Director_Jun_17'] = labelEnc.fit_transform(all_data['Director_Jun_17'])
all_data['VP_Jun_17'] = labelEnc.fit_transform(all_data['VP_Jun_17'])
#all_data['Sales_Person_Dec_17'] = labelEnc.fit_transform(all_data['Sales_Person_Dec_17'])
all_data['RSM_Dec_17'] = labelEnc.fit_transform(all_data['RSM_Dec_17'])
all_data['Director_Dec_17'] = labelEnc.fit_transform(all_data['Director_Dec_17'])
all_data['VP_Dec_17'] = labelEnc.fit_transform(all_data['VP_Dec_17'])

In [646]:
# Jun_17_sales
#sales_df = pd.DataFrame(data.Sales_Person_Jun_17.unique())
#sales_df.columns = ['Sales_Person_Jun_17']
#
#temp_data = pd.DataFrame(data.groupby(['Sales_Person_Jun_17', 'Attrition_Flag'])['UNIQUE_ID'].count().reset_index())
#temp_data_0 = sales_df.merge( temp_data[temp_data['Attrition_Flag']==0], on = 'Sales_Person_Jun_17')
#temp_data_0.columns = ['Sales_Person_Jun_17', 'Attrition_Flag_0', '0_count_s_J']
#temp_data_0['Sales_Person_Jun_17'] = temp_data_0['Sales_Person_Jun_17'].astype('str')
#
#temp_data_1 = sales_df.merge( temp_data[temp_data['Attrition_Flag']==1], on = 'Sales_Person_Jun_17')
#temp_data_1.columns = ['Sales_Person_Jun_17', 'Attrition_Flag_1', '1_count_s_J']
#temp_data_1['Sales_Person_Jun_17'] = temp_data_1['Sales_Person_Jun_17'].astype('str')
#temp_data1 = temp_data_1.merge(temp_data_0)
#temp_data1.head()
#
## Dec_17_sales
#del temp_data_0, temp_data_1
#sales_df = pd.DataFrame(data.Sales_Person_Dec_17.unique())
#sales_df.columns = ['Sales_Person_Dec_17']
#
#temp_data = pd.DataFrame(data.groupby(['Sales_Person_Dec_17', 'Attrition_Flag'])['UNIQUE_ID'].count().reset_index())
#temp_data_0 = sales_df.merge( temp_data[temp_data['Attrition_Flag']==0], on = 'Sales_Person_Dec_17')
#temp_data_0.columns = ['Sales_Person_Dec_17', 'Attrition_Flag_0', '0_count_s_D']
#temp_data_0['Sales_Person_Dec_17'] = temp_data_0['Sales_Person_Dec_17'].astype('str')
#
#temp_data_1 = sales_df.merge( temp_data[temp_data['Attrition_Flag']==1], on = 'Sales_Person_Dec_17')
#temp_data_1.columns = ['Sales_Person_Dec_17', 'Attrition_Flag_1', '1_count_s_D']
#temp_data_1['Sales_Person_Dec_17'] = temp_data_1['Sales_Person_Dec_17'].astype('str')
#temp_data2 = temp_data_1.merge(temp_data_0)
##print(temp_data2.head())
##print(temp_data1.head())
#
#temp_data1 = temp_data1.drop(['Attrition_Flag_0', 'Attrition_Flag_1'], axis= 1)
#temp_data1['Sales_Person_Jun_17'] = temp_data1['Sales_Person_Jun_17'].astype('str')
##temp_data1.info()
##temp_data1.unique()
#
#temp_data2 = temp_data2.drop(['Attrition_Flag_0', 'Attrition_Flag_1'], axis= 1)
#temp_data2['Sales_Person_Dec_17'] = temp_data2['Sales_Person_Dec_17'].astype('str')
#
#all_data['Sales_Person_Dec_17'] = all_data['Sales_Person_Dec_17'].astype('str')
#all_data['Sales_Person_Jun_17'] = all_data['Sales_Person_Jun_17'].astype('str')
#
##temp_data1.info()
#
#all_data = all_data.merge(temp_data1, how = 'left')
#all_data = all_data.merge(temp_data2, how = 'left')
##all_data['Sales_Person_Jun_17'].head()
#
#all_data['score_s_J'] = all_data['1_count_s_J']/all_data['0_count_s_J']
#all_data['score_s_D'] = all_data['1_count_s_D']/all_data['0_count_s_D']
#
##all_data['Sales_Person_Jun_17'] = labelEnc.fit_transform(all_data['Sales_Person_Jun_17'])
##all_data['Sales_Person_Dec_17'] = labelEnc.fit_transform(all_data['Sales_Person_Dec_17'])
#all_data=all_data.drop(['Sales_Person_Jun_17','Sales_Person_Dec_17'],axis=1)

In [647]:
#all_data['score_s_J'].fillna (0, inplace = True)
#all_data['1_count_s_J'].fillna (0, inplace = True)
#all_data['0_count_s_J'].fillna (0, inplace = True)
#all_data['score_s_D'].fillna (0, inplace = True)
#all_data['1_count_s_D'].fillna (0, inplace = True)
#all_data['0_count_s_D'].fillna (0, inplace = True)

In [648]:
#all_data['Sales_Person_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Sales_Person_Jun_17']]
#all_data['Sales_Person_Jun_17'] = all_data['Sales_Person_Jun_17'].astype('int32')

#all_data['RSM_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['RSM_Jun_17']]
#all_data['RSM_Jun_17'] = all_data['RSM_Jun_17'].astype('int32')

#all_data['Director_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Director_Jun_17']]
#all_data['Director_Jun_17'] = all_data['Director_Jun_17'].astype('int32')

#all_data['VP_Jun_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['VP_Jun_17']]
#all_data['VP_Jun_17'] = all_data['VP_Jun_17'].astype('int32')

#all_data['Sales_Person_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Sales_Person_Dec_17']]
#all_data['Sales_Person_Dec_17'] = all_data['Sales_Person_Dec_17'].astype('int32')

#all_data['RSM_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['RSM_Dec_17']]
#all_data['RSM_Dec_17'] = all_data['RSM_Dec_17'].astype('int32')

#all_data['Director_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['Director_Dec_17']]
#all_data['Director_Dec_17'] = all_data['Director_Dec_17'].astype('int32')

#all_data['VP_Dec_17'] = ['1' if x == 'Unassigned' else 0 for x in all_data['VP_Dec_17']]
#all_data['VP_Dec_17'] = all_data['VP_Dec_17'].astype('int32')

In [649]:
min(all_data['Rev_17_GeoPod']), max(all_data['Rev_17_GeoPod'])

(305.71, 538715.92)

In [650]:
#all_data.isnull().sum()
all_data = pd.get_dummies(all_data,columns=['Sales_Person_Jun_17', 'Sales_Person_Dec_17'], drop_first=True)

In [651]:
all_data.DataCorp_Market_Share.unique()
all_data['DataCorp_Market_Share'].fillna(np.mean(all_data.DataCorp_Market_Share), inplace = True)

In [652]:
all_data['Major_competitor_market_share'].fillna(round(np.mean(all_data.Major_competitor_market_share),2), inplace = True)
#all_data.Major_competitor_market_share.unique()

In [653]:
all_data['Other_competitor_market_share'].fillna(round(np.mean(all_data.Other_competitor_market_share),2), inplace = True)
#all_data.Other_competitor_market_share.unique()

In [654]:
all_data['Tenure_months'].fillna(round(np.mean(all_data.Tenure_months),2), inplace = True)
#all_data.Tenure_months.unique()

In [655]:
all_data['Count_Entities'].fillna(round(np.mean(all_data.Count_Entities),2), inplace = True)
#all_data.Count_Entities.unique()

In [656]:
all_data['Count_Jurisdicion'].fillna(round(np.mean(all_data.Count_Jurisdicion),2), inplace = True)
#all_data.Count_Jurisdicion.unique()
#all_data['Price_per_Unit'] = all_data['Rev_17_GeoPod'] / all_data['Vol_17_GeoPod']
#all_data['birth_death'] = all_data['Vol_17_Death_Event'] / (all_data['Vol_17_Birth_Event'] + 1)
#all_data['birth_death'].fillna((0), inplace = True)
#all_data['Share_Market'] = all_data['DataCorp_Market_Share'] - all_data['Major_competitor_market_share']
#all_data['Share_Market'] = [1 if x > 0 else 0 for x in all_data['Share_Market']]

In [657]:
all_data['Tenure_months'].fillna(round(np.mean(all_data['Tenure_months']),0), inplace = True)
all_data['Tenure_months_new'] = all_data['Tenure_months'].astype('int32')
all_data['Tenure_months_new'] = all_data['Tenure_months']
all_data['Tenure_months_new'] = [20 if x <= 20.0 and x >= 0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [40 if x > 20.0 and x <= 40.0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [60 if x > 40.0 and x <= 60.0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [80 if x > 60.0 and x <= 80.0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [100 if x > 80.0 and x <= 100.0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [150 if x > 100.0 and x <= 150.0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [200 if x > 150.0 and x <= 200.0 else x for x in all_data['Tenure_months_new']]
all_data['Tenure_months_new'] = [250 if x > 200.0 else x for x in all_data['Tenure_months_new']]

In [658]:
all_data.isnull().sum()

UNIQUE_ID                         0
Rev_17_GeoPod                     0
Rev_17_B                          0
Rev_17_C                          0
Vol_17_GeoPod                     0
Vol_17_B                          0
Vol_17_C                          0
Rev_17_GeoPod_Logistics           0
Rev_17_GeoPod_HR                  0
Rev_17_GeoPod_Finance             0
Vol_17_GeoPod_Logistics           0
Vol_17_GeoPod_HR                  0
Vol_17_GeoPod_Finance             0
Vol_17_Death_Event                0
Vol_17_Birth_Event                0
Vol_17_COA                        0
Vol_17_COA_Win                    0
Rev_17_D                          0
Rev_17_E                          0
Rev_17_F                          0
Rev_17_G                          0
Rev_17_H                          0
Rev_17_I                          0
Vol_17_D                          0
Vol_17_E                          0
Vol_17_F                          0
Vol_17_G                          0
Vol_17_H                    

# Training the model

In [659]:
#from catboost import CatBoostClassifier,Pool, cv
#from lightgbm import LGBMClassifier
from sklearn.model_selection import StratifiedKFold,train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score

In [660]:
df_train=all_data[all_data['Attrition_Flag'].isnull()==False].copy()
df_test=all_data[all_data['Attrition_Flag'].isnull()==True].copy()

df_train['Attrition_Flag'] = df_train['Attrition_Flag'].astype('int32')
print(df_train.shape,df_test.shape)

(14601, 304) (4000, 304)


In [661]:
X,y=df_train.drop(['UNIQUE_ID','Attrition_Flag'],axis=1),df_train['Attrition_Flag']
Xtest=df_test.drop(['UNIQUE_ID','Attrition_Flag'],axis=1)

#X = X.fillna(0)
#Xtest = Xtest.fillna(0)
print(X.shape,Xtest.shape)
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.20,random_state = 1996,stratify=y)

(14601, 302) (4000, 302)


In [662]:
X.isnull().sum()

Rev_17_GeoPod                     0
Rev_17_B                          0
Rev_17_C                          0
Vol_17_GeoPod                     0
Vol_17_B                          0
Vol_17_C                          0
Rev_17_GeoPod_Logistics           0
Rev_17_GeoPod_HR                  0
Rev_17_GeoPod_Finance             0
Vol_17_GeoPod_Logistics           0
Vol_17_GeoPod_HR                  0
Vol_17_GeoPod_Finance             0
Vol_17_Death_Event                0
Vol_17_Birth_Event                0
Vol_17_COA                        0
Vol_17_COA_Win                    0
Rev_17_D                          0
Rev_17_E                          0
Rev_17_F                          0
Rev_17_G                          0
Rev_17_H                          0
Rev_17_I                          0
Vol_17_D                          0
Vol_17_E                          0
Vol_17_F                          0
Vol_17_G                          0
Vol_17_H                          0
Vol_17_I                    

In [663]:
from sklearn.feature_selection import SelectFromModel

In [664]:
clf = RandomForestClassifier(n_estimators = 350)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [665]:
sel = SelectFromModel(clf)
sel.fit(X_train, y_train)

SelectFromModel(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
        max_features=None, norm_order=1, prefit=False, threshold=None)

In [666]:
selected_feat= X_train.columns[(sel.get_support())]
clf.fit(X_train[selected_feat], y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [667]:
predict = clf.predict(X_val[selected_feat])

In [668]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy = accuracy_score(predict, y_val)
confusion_matrix = confusion_matrix(predict, y_val)
print(accuracy)
print(confusion_matrix)

##0.891475522081479
#[[2487  254]
#[  63  117]]

#350
#0.8921602191030469
#[[2489  254]
# [  61  117]]

#350 sel feature
#0.8925025676138308
#[[2473  237]
# [  77  134]]

#Sales person one hot
#0.8938719616569668
#[[2473  233]
# [  77  138]]

0.8925025676138308
[[2476  240]
 [  74  131]]


In [513]:
imp = pd.DataFrame(selected_feat)

In [514]:
imp['Importance'] = clf.feature_importances_
imp

0  Importance
0                   Rev_17_GeoPod    0.039878
1                   Vol_17_GeoPod    0.033135
2         Rev_17_GeoPod_Logistics    0.024225
3           Rev_17_GeoPod_Finance    0.036753
4           Vol_17_GeoPod_Finance    0.031756
5              Vol_17_Death_Event    0.019394
6              Vol_17_Birth_Event    0.028040
7                      Vol_17_COA    0.027982
8                        Rev_17_D    0.020075
9                        Rev_17_G    0.029328
10                       Vol_17_D    0.020474
11                       Vol_17_G    0.024510
12          DataCorp_Market_Share    0.079369
13  Major_competitor_market_share    0.049959
14  Other_competitor_market_share    0.047126
15                  Tenure_months    0.102529
16                    Discount_17    0.022007
17                 Count_Entities    0.039643
18              Count_Jurisdicion    0.038672
19                    Price_Point    0.038641
20               Vol_16_GeoPod_HR    0.045195
21                       Vol_16_D    0.024791
22                    0_count_s_J    0.028228
23                    0_count_s_D    0.028957
24                      score_s_J    0.037991
25                      score_s_D    0.038879
26              Tenure_months_new    0.042461

In [515]:
imp.sort_values(by = ['Importance'], ascending = False)

0  Importance
15                  Tenure_months    0.102529
12          DataCorp_Market_Share    0.079369
13  Major_competitor_market_share    0.049959
14  Other_competitor_market_share    0.047126
20               Vol_16_GeoPod_HR    0.045195
26              Tenure_months_new    0.042461
0                   Rev_17_GeoPod    0.039878
17                 Count_Entities    0.039643
25                      score_s_D    0.038879
18              Count_Jurisdicion    0.038672
19                    Price_Point    0.038641
24                      score_s_J    0.037991
3           Rev_17_GeoPod_Finance    0.036753
1                   Vol_17_GeoPod    0.033135
4           Vol_17_GeoPod_Finance    0.031756
9                        Rev_17_G    0.029328
23                    0_count_s_D    0.028957
22                    0_count_s_J    0.028228
6              Vol_17_Birth_Event    0.028040
7                      Vol_17_COA    0.027982
21                       Vol_16_D    0.024791
11                       Vol_17_G    0.024510
2         Rev_17_GeoPod_Logistics    0.024225
16                    Discount_17    0.022007
10                       Vol_17_D    0.020474
8                        Rev_17_D    0.020075
5              Vol_17_Death_Event    0.019394

### Tuning

In [596]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 600, num = 50)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 100, num = 5)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [606]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 20, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train[selected_feat], y_train)

Fitting 3 folds for each of 20 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:  4.8min finished


RandomizedSearchCV(cv=3, error_score='raise-deprecating',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          fit_params=None, iid='warn', n_iter=20, n_jobs=-1,
          param_distributions={'n_estimators': [200, 208, 216, 224, 232, 240, 248, 257, 265, 273, 281, 289, 297, 306, 314, 322, 330, 338, 346, 355, 363, 371, 379, 387, 395, 404, 412, 420, 428, 436, 444, 453, 461, 469, 477, 485, 493, 502, 510, 518, 526, 534, 542, 551, 559, 567, 575, 583, 591, 600], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 32, 55, 77, 100, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 

In [674]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy
#params=rf_random.best_params_
#print(params)
## 0.8955837042108867
#[[2481  240]
# [  69  131]]
base_model = RandomForestClassifier(n_estimators=208, min_samples_split=10, min_samples_leaf=1, max_features='sqrt', max_depth=None, bootstrap=True)
#base_model = RandomForestClassifier(n_estimators=208, min_samples_split=5, min_samples_leaf=2, max_features='sqrt', max_depth=None, bootstrap=True)
base_model.fit(X_train[selected_feat], y_train)
#base_accuracy = evaluate(base_model, X_val[selected_feat], y_val)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=208, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [675]:
from sklearn.metrics import accuracy_score,confusion_matrix
predict = base_model.predict(X_val[selected_feat])
accuracy = accuracy_score(predict, y_val)
#print(y_train)
#print(type(list(y_train)))
confusion_matrix_ = confusion_matrix(predict, y_val)
print(accuracy)
print(confusion_matrix_)

0.8931872646353989
[[2481  243]
 [  69  128]]


In [678]:
predict = base_model.predict(Xtest[selected_feat])
df_test['Output'] = predict

In [679]:
print(df_test[['UNIQUE_ID', 'Output']])

        UNIQUE_ID  Output
14601          23       0
14602          29       0
14603          52       0
14604          88       0
14605         134       1
14606         163       0
14607         190       0
14608         197       0
14609         267       0
14610         277       0
14611         282       0
14612         364       0
14613         422       0
14614         455       0
14615         460       0
14616         464       0
14617         472       0
14618         493       0
14619         511       0
14620         536       0
14621         559       0
14622         572       0
14623         629       0
14624         639       0
14625         640       0
14626         692       0
14627         746       0
14628         753       0
14629         824       0
14630         831       0
...           ...     ...
18571  9401518645       0
18572  9401521096       1
18573  9401522994       0
18574  9401523516       0
18575  9401523530       1
18576  9401523939       0
18577  94015

In [680]:
df_test[['UNIQUE_ID', 'Output']].to_csv('D:\PGDBA\Competitions\EXL-Acumen\Final.csv')